// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetServiceStatuses():Promise<Record<string, boolean>>;

export function LoadConfig():Promise<config.AppConfig>;

export function OpenBrowser(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function StartServices():Promise<void>;

export function StopServices():Promise<void>;
